---
branches:
  - name: master
  - name: develop
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - successComment: false
      failComment: false
