#!/bin/bash

export REPO="${GITHUB_REPOSITORY##*/}"
export VERSION="${GITHUB_REF##*/v}"
export VERSION_SPLIT=(${VERSION//./ })

export VERSION_PRERELEASE="-${VERSION#*-}"
[ "$VERSION_PRERELEASE" == "-$VERSION" ] && export VERSION_PRERELEASE=""

export VERSION_MAJOR="${VERSION_SPLIT[0]}${VERSION_PRERELEASE}"
export VERSION_MINOR="${VERSION_SPLIT[0]}.${VERSION_SPLIT[1]}${VERSION_PRERELEASE}"
export VERSION_PATCH="${VERSION}"

echo "REPO: $REPO"
echo "VERSION: $VERSION"
echo "VERSION_PRERELEASE: $VERSION_PRERELEASE"
echo "VERSION_MAJOR: $VERSION_MAJOR"
echo "VERSION_MINOR: $VERSION_MINOR"
